# Generated by Django 5.2.4 on 2025-08-30 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_product'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
